interface ICurrency {
  id: number;
  name: string;
  mark?: string;
  code?: string;
}
export const allCurrencies: Array<ICurrency> = [
{id: 1, name: 'Leke', mark: 'Lek', code: 'ALL'},
{id: 2, name: 'US Dollar', mark: '$', code: 'USD'},
{id: 3, name: 'Afghanis', mark: '؋', code: 'AFN'},
{id: 4, name: 'Pesos', mark: '$', code: 'ARS'},
{id: 5, name: 'Guilders', mark: 'ƒ', code: 'AWG'},
{id: 6, name: 'Australian Dollar', mark: '$', code: 'AUD'},
{id: 7, name: 'New Manats', mark: 'ман', code: 'AZN'},
{id: 8, name: 'Rubles', mark: 'p.', code: 'BYR'},
{id: 9, name: 'Euro', mark: '€', code: 'EUR'},
{id: 10, name: 'Bolivianos', mark: '$b', code: 'BOB'},
{id: 11, name: 'Convertible Marka', mark: 'KM', code: 'BAM'},
{id: 12, name: 'Pula', mark: 'P', code: 'BWP'},
{id: 13, name: 'Leva', mark: 'лв', code: 'BGN'},
{id: 14, name: 'Reals', mark: 'R$', code: 'BRL'},
{id: 15, name: 'British Pounds', mark: '£', code: 'GBP'},
{id: 16, name: 'Riels', mark: '៛', code: 'KHR'},
{id: 17, name: 'Canadian Dollar', mark: '$', code: 'CAD'},
{id: 18, name: 'Pesos', mark: '$', code: 'CLP'},
{id: 19, name: 'Yuan Renminbi', mark: '¥', code: 'CNY'},
{id: 20, name: 'Pesos', mark: '$', code: 'COP'},
{id: 21, name: 'Colón', mark: '₡', code: 'CRC'},
{id: 22, name: 'Kuna', mark: 'kn', code: 'HRK'},
{id: 23, name: 'Pesos', mark: '₱', code: 'CUP'},
{id: 24, name: 'Koruny', mark: 'Kč', code: 'CZK'},
{id: 25, name: 'Kroner', mark: 'kr', code: 'DKK'},
{id: 26, name: 'Pesos', mark: 'RD$', code: 'DOP '},
{id: 27, name: 'Pounds', mark: '£', code: 'EGP'},
{id: 28, name: 'Colones', mark: '$', code: 'SVC'},
{id: 29, name: 'Pounds', mark: '£', code: 'FKP'},
{id: 30, name: 'Cedis', mark: '¢', code: 'GHC'},
{id: 31, name: 'Pounds', mark: '£', code: 'GIP'},
{id: 32, name: 'Quetzales', mark: 'Q', code: 'GTQ'},
{id: 33, name: 'Pounds', mark: '£', code: 'GGP'},
{id: 34, name: 'Lempiras', mark: 'L', code: 'HNL'},
{id: 35, name: 'Hong Kong Dollar', mark: '$', code: 'HKD'},
{id: 36, name: 'Forint', mark: 'Ft', code: 'HUF'},
{id: 37, name: 'Kronur', mark: 'kr', code: 'ISK'},
{id: 38, name: 'Rupees', mark: 'Rp', code: 'INR'},
{id: 39, name: 'Rupiahs', mark: 'Rp', code: 'IDR'},
{id: 40, name: 'Rials', mark: '﷼', code: 'IRR'},
{id: 41, name: 'Pounds', mark: '£', code: 'IMP'},
{id: 42, name: 'New Shekels', mark: '₪', code: 'ILS'},
{id: 43, name: 'Yen', mark: '¥', code: 'JPY'},
{id: 44, name: 'Pounds', mark: '£', code: 'JEP'},
{id: 45, name: 'Tenge', mark: 'лв', code: 'KZT'},
{id: 46, name: 'Won', mark: '₩', code: 'KPW'},
{id: 47, name: 'Won', mark: '₩', code: 'KRW'},
{id: 48, name: 'Soms', mark: 'лв', code: 'KGS'},
{id: 49, name: 'Kips', mark: '₭', code: 'LAK'},
{id: 50, name: 'Lati', mark: 'Ls', code: 'LVL'},
{id: 51, name: 'Pounds', mark: '£', code: 'LBP'},
{id: 52, name: 'Switzerland Francs', mark: 'CHF', code: 'CHF'},
{id: 53, name: 'Litai', mark: 'Lt', code: 'LTL'},
{id: 54, name: 'Denars', mark: 'ден', code: 'MKD'},
{id: 55, name: 'Ringgits', mark: 'RM', code: 'MYR'},
{id: 56, name: 'Rupees', mark: '₨', code: 'MUR'},
{id: 57, name: 'Pesos', mark: '$', code: 'MXN'},
{id: 58, name: 'Tugriks', mark: '₮', code: 'MNT'},
{id: 59, name: 'Meticais', mark: 'MT', code: 'MZN'},
{id: 60, name: 'Rupees', mark: '₨', code: 'NPR'},
{id: 61, name: 'Guilders', mark: 'ƒ', code: 'ANG'},
{id: 62, name: 'New Zealand Dollar', mark: '$', code: 'NZD'},
{id: 63, name: 'Cordobas', mark: 'C$', code: 'NIO'},
{id: 64, name: 'Nairas', mark: '₦', code: 'NGN'},
{id: 65, name: 'Krone', mark: 'kr', code: 'NOK'},
{id: 66, name: 'Rials', mark: '﷼', code: 'OMR'},
{id: 67, name: 'Rupees', mark: '₨', code: 'PKR'},
{id: 68, name: 'Balboa', mark: 'B/.', code: 'PAB'},
{id: 69, name: 'Guarani', mark: 'Gs', code: 'PYG'},
{id: 70, name: 'Nuevos Soles', mark: 'S/.', code: 'PEN'},
{id: 71, name: 'Pesos', mark: 'Php', code: 'PHP'},
{id: 72, name: 'Zlotych', mark: 'zł', code: 'PLN'},
{id: 73, name: 'Rials', mark: '﷼', code: 'QAR'},
{id: 74, name: 'New Lei', mark: 'lei', code: 'RON'},
{id: 75, name: 'Rubles', mark: 'руб', code: 'RUB'},
{id: 76, name: 'Pounds', mark: '£', code: 'SHP'},
{id: 77, name: 'Riyals', mark: '﷼', code: 'SAR'},
{id: 78, name: 'Dinars', mark: 'Дин.', code: 'RSD'},
{id: 79, name: 'Rupees', mark: '₨', code: 'SCR'},
{id: 80, name: 'Shillings', mark: 'S', code: 'SOS'},
{id: 81, name: 'Rand', mark: 'R', code: 'ZAR'},
{id: 82, name: 'Rupees', mark: '₨', code: 'LKR'},
{id: 83, name: 'Kronor', mark: 'kr', code: 'SEK'},
{id: 84, name: 'Pounds', mark: '£', code: 'SYP'},
{id: 85, name: 'Baht', mark: '฿', code: 'THB'},
{id: 86, name: 'Lira', mark: '₺', code: 'TRY'},
{id: 87, name: 'Liras', mark: '£', code: 'TRL'},
{id: 88, name: 'Hryvnia', mark: '₴', code: 'UAH'},
{id: 89, name: 'Pesos', mark: '$U', code: 'UYU'},
{id: 90, name: 'Sums', mark: 'лв', code: 'UZS'},
{id: 91, name: 'Bolivares Fuertes', mark: 'Bs', code: 'VEF'},
{id: 92, name: 'Dong', mark: '₫', code: 'VND'},
{id: 93, name: 'Rials', mark: '﷼', code: 'YER'},
{id: 94, name: 'Zimbabwe Dollar', mark: 'Z$', code: 'ZWD'},
{id: 95, name: 'Rupees', mark: '₹', code: 'INR'},
{id: 96, name: 'Kuwaiti Dinar', mark: 'KD', code: 'KWD'},
{id: 97, name: 'UAE Dirham', mark: 'د.إ', code: 'AED'}
];
